config/routes.rb
Rails.application.routes.draw do
  devise_for(
    :admin_users,
    ActiveAdmin::Devise.config
  )
  ActiveAdmin.routes(self)
  devise_for(
    :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks'
    }
  )

  get(
    'index',
    to: 'home#index',
    as: 'home'
  )

  get(
    'mobile_app',
    to: 'home#mobile_app',
    as: 'mobileapp'
  )

  root 'fretx#player'

  #Api
  namespace :api do
    namespace :v1 do
      get(
        '/songs/index',
        to: 'songs#index'
      )
      get(
        '/songs/list',
        to: 'songs#list'
      )
      get(
        '/songs/:youtube_id-:id',
        to: 'songs#show'
      )
      get(
        '/mysongs',
        to: 'songs#mysongs'
      )
      get(
        '/youtube/videodata/:id',
        to: 'youtube#videodata'
      )
      get(
        '/chords',
        to: 'chords#index'
      )
      get(
        '/chords/:chordname',
        to: 'chords#show'
        )
      get(
        '/autocompletes/get_select_data',
        to: 'autocompletes#get_select_data'
        )
      get(
        '/get_related_songs',
        to: 'songs#get_related_songs'
        )
      get(
        '/get_searched_song',
        to: 'songs#get_searched_song'
        )
      get(
        '/get_promotion_video',
        to: 'songs#get_promotion_video'
        )
      post(
        '/add',
        to: 'songs#add'
        )
      post(
        '/save_song',
        to: 'songs#save_song'
        )
    end
  end
  get "/player", to: "fretx#player"
  get "/list",   to: "fretx#list"
  get "/editor", to: "fretx#editor"
  get "/player/:youtube_id-:id", to: "fretx#player"
  post "/create_new_song", to: "fretx#create_new_song"
  get "/editor/:youtube_id-:id", to: "fretx#editor"
end

app/views/layouts/_header.html.haml
%header
  .container
    %a.logo{ href: root_path }
      = image_tag 'logo.png', alt: 'FretX'

    %a.btn.get-fretx{ href: "https://store.fretx.rocks/collections/frontpage" }
      = image_tag 'rock-ico.png'
      Get FretX

    #userview_container.header-links
      - if current_user.blank?
        / %a{ href: "#", 'data-toggle': "modal", 'data-target': '#signupModal' }
        /   Sign Up
        - unless request.user_agent =~ /Mobile|webOS/
          %a{ href: "#", 'data-toggle': "modal", 'data-target': "#loginModal" }
            Add Your Songs
      - else
        %ul.list-unstyled
          %li.dropdown.txt
            %a#logout.dropdown-toggle{"data-toggle": "dropdown", href: "#"}
              = current_user.name
            %ul.dropdown-menu
              - unless current_user.blank?
                %li
                  %a.submenu{ "data-target" => "#my-song", "data-toggle" => "modal", type: "button" } My Songs
              %li
                = link_to 'Editor', editor_path, class: 'submenu'
              %li
                = link_to 'Logout', destroy_user_session_path, method: 'delete', class: 'submenu'

- unless current_user.blank?
  #my-song.modal.fade{role: "dialog"}
    .modal-dialog
      .modal-content.player-top-btns
        .modal-header
          %button.close{"data-dismiss" => "modal", type: "button"} ×
          %h4.modal-title My Songs
        .modal-body
          - if @my_songs
            %table.table
              - @my_songs.each do |song|
                %tr
                  %td
                    %a.song{ href: "/#{action_name == 'editor' ? 'editor' : 'player' }/#{song.youtube_id}-#{song.id}" }
                      %img{ src: "//img.youtube.com/vi/#{song.youtube_id}/1.jpg" }/
                  %td{ width: '80%' }
                    %a.song{ href: "/#{action_name == 'editor' ? 'editor' : 'player' }/#{song.youtube_id}-#{song.id}" }
                      %h4 #{song.artist == nil ? '[No Artist]' :  song.artist}
                      %h5 #{song.song_title == nil ? '[No Title]' :  song.song_title}

- if current_user.blank?
  #loginModal.modal.fade.login-signup-flow{ tabindex: "-1", role: "dialog" }
    .modal-dialog
      .modal-content
        .modal-body
          %a{ href: user_facebook_omniauth_authorize_path, class: "btn fb" }
            = image_tag 'fb-ico.svg', alt: "Login with Facebook"
            Login with Facebook
          / .account-separated
          /   %h4
          /     Don't have an account?
          /   %a{ href: '#', 'data-toggle': 'modal', 'data-target': '#signupModal', 'data-dismiss': 'modal', class: 'modal-redirect' }
          /     Sign Up

  / #signupModal.modal.fade.login-signup-flow{ tabindex: "-1", role: "dialog" }
  /   .modal-dialog
  /     .modal-content
  /       .modal-body
  /         %h3
  /           Signup today
  /         %a{ href: user_facebook_omniauth_authorize_path, class: "btn fb" }
  /           = image_tag "fb-ico.svg", alt: "Sign up with Facebook"
  /           Sign up with Facebook
  /         .account-separated
  /           %h4
  /             Already a member?
  /           %a{ href: "#", 'data-toggle': 'modal', 'data-target': "#loginModal", 'data-dismiss': "modal", class: "modal-redirect" }
  /             Login

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:content => "https://s3.eu-central-1.amazonaws.com/fretx.rocks/Facebook+share+1200x1200.png", :property => "og:image"}/
    %meta{:content => "FretX", :property => "og:site_name"}/
    %meta{:content => "The BEST Platform to LEARN songs", :property => "og:title"}/
    %meta{:content => "FretX platform shows you how to play songs in FUN and DYNAMIC Way! Click HERE and START TODAY", :property => "og:description"}/
    %title #{ ENV['APPLICATION_NAME'] }
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = yield :javascripts
    = yield :stylesheets
  %body
    = render 'layouts/header'
    = yield